module.exports.ERROR_CODE = {
  BAD_REQUEST: "BAD_REQUEST",
  INVALID_FILE_FORMAT: "INVALID_FILE_FORMAT",
  INVALID_REQUEST: "INVALID_REQUEST",
  RESOURCE_NOT_FOUND: "RESOURCE_NOT_FOUND",
};

module.exports.ERROR_NAME = {
  REQUEST_ERROR: "RequestError",
  RESOURCE_ERROR: "ResourceError",
};
